'learningRates': [0.001,0.0001]
'numEpochs': [14,4]
'batchSize': 512   
'sampRate': 16000
'numSamples': 16000
'trainLimitInput': 0
'validationPercentage': 10
'unknownPercentage': 10
'silencePercentage': 10
'silenceFileName':   '_silence_'
'maxShiftSamps': 160
'backgroundLabel': '_background_noise_'
'backgroundMinVol': 0.1  
'backgroundMaxVol': 0.5
'mfccWindowLen':  0.03
'mfccWindowStride': 0.01
'mfccNumCep': 40
'mfccLowHz': 300
'mfccHighHz': 3400
